import favicon from "@/public/favicon.png";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<header className="h-20">
					<div className="relative aspect-square h-full">
						<Image
							src={favicon.src}
							alt="favicon"
							fill
							className="object-contain"
						/>
					</div>
				</header>

				{children}
			</body>
		</html>
	);
}
